// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdj-NMOqUyuYf1b_MvUtef0lkLYt8w1ho',
    appId: '1:885938522962:web:94944d637861d34ade088b',
    messagingSenderId: '885938522962',
    projectId: 'rockipoint',
    authDomain: 'rockipoint.firebaseapp.com',
    storageBucket: 'rockipoint.appspot.com',
    measurementId: 'G-4S3C7JGKM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_GZ9XpXrNN_dLHHA3W6IMS2UPUfZHHa8',
    appId: '1:885938522962:android:fcacdd51081b9caede088b',
    messagingSenderId: '885938522962',
    projectId: 'rockipoint',
    storageBucket: 'rockipoint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpgAYt8hhCh_vU69LJFZHelb-7832p8hY',
    appId: '1:885938522962:ios:6344b0c57c1e2fb6de088b',
    messagingSenderId: '885938522962',
    projectId: 'rockipoint',
    storageBucket: 'rockipoint.appspot.com',
    iosBundleId: 'com.example.rockiPoinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpgAYt8hhCh_vU69LJFZHelb-7832p8hY',
    appId: '1:885938522962:ios:6344b0c57c1e2fb6de088b',
    messagingSenderId: '885938522962',
    projectId: 'rockipoint',
    storageBucket: 'rockipoint.appspot.com',
    iosBundleId: 'com.example.rockiPoinApp',
  );
}
